### ISSUE TITLE
Add New Data Types

### ISSUE THREAD

**Issue by cutaway** [numat/clickplc#107]
The CLICKs appears to have [memory types](https://accautomation.ca/click-plc-numbering-system-and-addressing/) that are not supported here. I've exported the addresses which have the memory types and Modbus address in case you (or someone else) wants to add them. (sorry, currently don't have time myself).

My build, in case it is relevant for the data in the attached file is: CLICKPLUS PLC C2-03CPU-2 and two C2-08DR-6V modules.

[CLICKPLUS_C2-03CPU-2_w2_C2-08DR-6V_V.7_3.41_Modbus_Addresses.csv](https://github.com/numat/clickplc/files/15081899/CLICKPLUS_C2-03CPU-2_w2_C2-08DR-6V_V.7_3.41_Modbus_Addresses.csv)

**Comment by alexrudd2** [comment]
Thanks for posting this!

I no longer have access to physical PLCs right now, and therefore don't have plans to add the other types.  Some are already listed as separate issues. As far as I can tell those memory types were there in the original Click and unchanged for the 2021 Click Plus.

**Comment by alexrudd2** [comment]
- [x] Input Point (X)
- [x] Output Point (Y)
- [x] Control Relay (C)
- [ ] Timer (T) - https://github.com/numat/clickplc/issues/21
- [ ] Counter (CT)
- [ ] System Control Bit (SC)
- [ ] Data Registers 
    - [x] DS
    - [ ] DD
    - [ ] DH
    - [x] DF
- [ ] Input Register (XD)
- [ ] Output Register (TD)
- [ ] Timer Register (TD)
- [x] Counter Register (CTD)
- [ ] System Data Register (SD) - https://github.com/numat/clickplc/issues/13
- [ ] Text (TXT) - https://github.com/numat/clickplc/issues/100

**Comment by alexrudd2** [comment]
Are there any you need more than others, @cutaway ?

**Comment by alexrudd2** [comment]
Tracked (with more progress) here: https://github.com/alexrudd2/clickplc/issues/3
