### ISSUE TITLE
Error when running script clickplc, is it a bug

### ISSUE THREAD

**Issue by jimtal001** [numat/clickplc#16]
I'm running on ubuntu.  everything successfully installed My python version is 3.9.5.

When I run the python script **clickplc** 
$ python3 clickplc 192.168.13.100

where my plc ip address is: 192.168.13.100

I get the following error:

Traceback (most recent call last):
  File ".../.local/bin/./clickplc", line 8, in <module>
    sys.exit(command_line())
  File "/.../.local/lib/python3.9/site-packages/clickplc/__init__.py", line 19, in command_line
    parser.add_argument('tags_file', default=None, required=False,
  File "/usr/lib/python3.9/argparse.py", line 1410, in add_argument
    kwargs = self._get_positional_kwargs(*args, **kwargs)
  File "/usr/lib/python3.9/argparse.py", line 1526, in _get_positional_kwargs
    raise TypeError(msg)
TypeError: 'required' is an invalid argument for positionals

**Comment by JamesJeffryes** [comment]
I've released a new version of the driver, 0.3.4, that should avoid this issue.

**Comment by jimtal001** [comment]
Hello James,

I'll try out the new version.  Thanks!!!

**Comment by jimtal001** [comment]
Hello James,

I've been working with the new version of your clickplc library and I am
seeing an issue when requesting the C type addresses.  I do not see this
issue when requesting the DS type addresses.

for example, If I issue the command:
print(await plc.get('C1-C12'))
The returned dictionary object does not match the requested object size; it
returns C1-C16 but theC13-C16 values are incorrect.

Best Regards
Jim

**Comment by JamesJeffryes** [comment]
Click's have a querk where they only return C-type data an entire byte (8 coils) at a time. That means that your request is getting rounded up to the nearest multiple of 8. I can add some post-processing to drop the extra values on these requests.

**Comment by jimtal001** [comment]
Thanks for the response.
