### ISSUE TITLE
Unable to use CTD (Counter Current Values)

### ISSUE THREAD

**Issue by alexrudd2** [numat/clickplc#22]
Received via email

> Thank you so much for all of your hard work with the ClickPLC module for python. It has been extremely helpful at our facility. 
> 
> I seem to have run into a small issue, however, that I'm wondering if you can help push me in the right direction. As I'm new to coding, I cannot seem to figure out how to utilize the CTD (Counter Current Values) in python. I have attempted to add it via the driver, but I keep on receiving an error message ('H' format requires 0 <= number <= 65535).
> 
> Am I approaching this method the wrong way or is there an easier alternative? We would like to receive real-time count data from a sensor that we can view from anywhere in our facility.
> 
> Sorry for the newbie questions and thank you for taking the time to read this.
> 
> - Brandon

**Comment by bclapp94** [comment]
It appears that this issue occurs when the Modbus address is above 65535. For instance, when using the current code for SD, it will generate this same error, because the starting address is written as 361441. Using the last 5 digits, 61441, fixes the code. With that said, removing the first digit and utilizing code written in the driver, I was able to get the CTD function to work.

**Comment by alexrudd2** [comment]
Good job troubleshooting! If you'd like to open a pull request, we can likely merge your improved code into our repository and release it onto PyPI.  To do this, you'll need to fork `numat/clickplc` publicly into `bclapp94/clickplc` with the button next to Star.  
<img width="576" alt="Screen Shot 2021-12-13 at 9 35 39 AM" src="https://user-images.githubusercontent.com/52292902/145841301-59b70e43-1bf5-4268-879a-b056432172a6.png">
 Then you can commit your code edits to your forked repository, which will cause it to diverge from ours.  At that point, opening a new Pull Request will show the changes and allow for discussion.  [Here](https://github.com/numat/clickplc/pull/8)'s an example.
