### ISSUE TITLE
ClickPLC DS

### ISSUE THREAD

**Issue by mikeIFTS** [numat/clickplc#3]
First of all, thank you for creating this library! Its working pretty well for a PLC we have available to us. We are trying to add the DS register to the library (and hopefully give you a PR with it working), but have run into a snag. I cant find the 1 bit notation. I am currently working with a C0-12DD2E-D model. 

I am currently using the `_get_df` function as a template to add the register:
```python
    async def _get_df(self, start, end):
        """Read DF registers. Called by `get`.

        DF entries start at Modbus address 28672 (28673 in the Click software's
        1-indexed notation). Each DF entry takes 32 bits, or 2 16-bit
        registers.
        """
        if start < 1 or start > 500:
            raise ValueError('DF must be in [1, 500]')
        if end is not None and (end < 1 or end > 500):
            raise ValueError('DF end must be in [1, 500]')

        address = 28672 + 2 * (start - 1)
        count = 2 * (1 if end is None else (end - start + 1))
        registers = await self.read_registers(address, count)
        decoder = BinaryPayloadDecoder.fromRegisters(registers,
                                                     byteorder=Endian.Big,
                                                     wordorder=Endian.Little)
        if end is None:
            return decoder.decode_32bit_float()
        return {f'df{n}': decoder.decode_32bit_float() for n in range(start, end + 1)}
```

and added the ds register like:
```python
    async def _get_ds(self, start, end):
        """Read DS registers. Called by `get`.

        TODO: Make sure the address is correct!!
        DS entries start at Modbus address 40000 (40001 in the Click software's
        1-indexed notation). Each DS entry takes 32 bits, or 2 16-bit
        registers.
        """
        if start < 1 or start > 4500:
            raise ValueError('DF must be in [1, 500]')
        if end is not None and (end < 1 or end > 500):
            raise ValueError('DF end must be in [1, 500]')

        address = 400001 + start # <<< This is incorrect. Need to find the correct 1-bit address!
        count = 2 * (1 if end is None else (end - start + 1))
        registers = await self.read_registers(address, count)
        decoder = BinaryPayloadDecoder.fromRegisters(registers,
                                                     byteorder=Endian.Big,
                                                     wordorder=Endian.Little)
        if end is None:
            return decoder.decode_32bit_float()
        return {f'ds{n}': decoder.decode_32bit_float() for n in range(start, end + 1)}
```

I expect I will need to look at the output to convert into an integer from the payload after getting the correct address. 

Im taking a look at:
![Capture](https://user-images.githubusercontent.com/48768927/70827105-67658980-1d9d-11ea-8cee-ca15009d8a65.PNG)

Where can I find the Click software's 1-indexed notation? Am I missing something?

**Comment by patrickfuller** [comment]
Thanks for contributing back to this library, and I’m happy to help!

Modbus has quirks (to say it nicely) that need to be managed.

Your starting address of 400001 is 1-indexed, the first number ends with 1 instead of 0. In modbus world, that 4 is also ignored for address counting.

This means that, in pymodbus’s 0-indexed notation, your starting address is 0. read_holding_registers(0, count) should work.

Hope this helps and let me know if you have any other questions!

**Comment by patrickfuller** [comment]
You're really close so I'll send you what I think it should look like. Have a go and let me know if it works.

    async def _get_ds(self, start, end):
        """Read DS registers. Called by `get`.

        DS entries start at Modbus address 0 (1 in the Click software's
        1-indexed notation). Each DS entry takes one 16-bit register.
        """
        if start < 1 or start > 500:
            raise ValueError('DF must be in [1, 500]')
        if end is not None and (end < 1 or end > 500):
            raise ValueError('DF end must be in [1, 500]')

        address = start
        count = (1 if end is None else (end - start + 1))
        registers = await self.read_registers(address, count)
        decoder = BinaryPayloadDecoder.fromRegisters(registers,
                                                     byteorder=Endian.Big,
                                                     wordorder=Endian.Little)
        if end is None:
            return decoder.decode_16bit_int() . # Might have to be decode_16bit_uint() if unsigned
        return {f'ds{n}': decoder.decode_16bit_int() for n in range(start, end + 1)}
```
