### ISSUE TITLE
Is it possible to add 'C' values to this code?

### ISSUE THREAD

**Issue by MacItaly311** [numat/clickplc#6]
What a wonderful module! I appreciate the integration of Python with the Click PLCs. Thank you for the time invested in creating this. 

I would love to see the integration of the 'C' values. Most of my Click code relies heavily on internal relays and to be able to control them from a Python GUI I create would be extremely beneficial and helpful.

**Comment by patrickfuller** [comment]
@MacItaly311 just added this.

Tested quickly on one PLC but it's not fully tested. Please let me know how it works out!

**Comment by MacItaly311** [comment]
Wonderful job! Thank you! All looks well on my end!
